// Code generated by protoc-gen-go.
// source: gosync.proto
// DO NOT EDIT!

/*
Package gosync is a generated protocol buffer package.

It is generated from these files:
	gosync.proto

It has these top-level messages:
	GetEventsRequest
	GSMessage
	Session
	JoinRequest
	JoinReply
	PublishRequest
	PublishResult
*/
package gosync

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetEventsRequest struct {
	Session    *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	GuestId    int32    `protobuf:"varint,2,opt,name=guest_id,json=guestId" json:"guest_id,omitempty"`
	NtpTimeRtt int32    `protobuf:"varint,5,opt,name=ntp_time_rtt,json=ntpTimeRtt" json:"ntp_time_rtt,omitempty"`
}

func (m *GetEventsRequest) Reset()                    { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()               {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetEventsRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type GSMessage struct {
	Time    int32  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *GSMessage) Reset()                    { *m = GSMessage{} }
func (m *GSMessage) String() string            { return proto.CompactTextString(m) }
func (*GSMessage) ProtoMessage()               {}
func (*GSMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Session struct {
	SessionId   string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	SessionName string `protobuf:"bytes,2,opt,name=session_name,json=sessionName" json:"session_name,omitempty"`
	NtpHost     string `protobuf:"bytes,3,opt,name=ntp_host,json=ntpHost" json:"ntp_host,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type JoinRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type JoinReply struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	GuestId int32    `protobuf:"varint,2,opt,name=guest_id,json=guestId" json:"guest_id,omitempty"`
}

func (m *JoinReply) Reset()                    { *m = JoinReply{} }
func (m *JoinReply) String() string            { return proto.CompactTextString(m) }
func (*JoinReply) ProtoMessage()               {}
func (*JoinReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *JoinReply) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type PublishRequest struct {
	Session *Session   `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Message *GSMessage `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *PublishRequest) Reset()                    { *m = PublishRequest{} }
func (m *PublishRequest) String() string            { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()               {}
func (*PublishRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PublishRequest) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *PublishRequest) GetMessage() *GSMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type PublishResult struct {
}

func (m *PublishResult) Reset()                    { *m = PublishResult{} }
func (m *PublishResult) String() string            { return proto.CompactTextString(m) }
func (*PublishResult) ProtoMessage()               {}
func (*PublishResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*GetEventsRequest)(nil), "gosync.GetEventsRequest")
	proto.RegisterType((*GSMessage)(nil), "gosync.GSMessage")
	proto.RegisterType((*Session)(nil), "gosync.Session")
	proto.RegisterType((*JoinRequest)(nil), "gosync.JoinRequest")
	proto.RegisterType((*JoinReply)(nil), "gosync.JoinReply")
	proto.RegisterType((*PublishRequest)(nil), "gosync.PublishRequest")
	proto.RegisterType((*PublishResult)(nil), "gosync.PublishResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for GoSync service

type GoSyncClient interface {
	JoinSession(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (GoSync_GetEventsClient, error)
	PublishEvent(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResult, error)
}

type goSyncClient struct {
	cc *grpc.ClientConn
}

func NewGoSyncClient(cc *grpc.ClientConn) GoSyncClient {
	return &goSyncClient{cc}
}

func (c *goSyncClient) JoinSession(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := grpc.Invoke(ctx, "/gosync.GoSync/JoinSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSyncClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (GoSync_GetEventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GoSync_serviceDesc.Streams[0], c.cc, "/gosync.GoSync/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &goSyncGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoSync_GetEventsClient interface {
	Recv() (*GSMessage, error)
	grpc.ClientStream
}

type goSyncGetEventsClient struct {
	grpc.ClientStream
}

func (x *goSyncGetEventsClient) Recv() (*GSMessage, error) {
	m := new(GSMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goSyncClient) PublishEvent(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResult, error) {
	out := new(PublishResult)
	err := grpc.Invoke(ctx, "/gosync.GoSync/PublishEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoSync service

type GoSyncServer interface {
	JoinSession(context.Context, *JoinRequest) (*JoinReply, error)
	GetEvents(*GetEventsRequest, GoSync_GetEventsServer) error
	PublishEvent(context.Context, *PublishRequest) (*PublishResult, error)
}

func RegisterGoSyncServer(s *grpc.Server, srv GoSyncServer) {
	s.RegisterService(&_GoSync_serviceDesc, srv)
}

func _GoSync_JoinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSyncServer).JoinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gosync.GoSync/JoinSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSyncServer).JoinSession(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSync_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoSyncServer).GetEvents(m, &goSyncGetEventsServer{stream})
}

type GoSync_GetEventsServer interface {
	Send(*GSMessage) error
	grpc.ServerStream
}

type goSyncGetEventsServer struct {
	grpc.ServerStream
}

func (x *goSyncGetEventsServer) Send(m *GSMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _GoSync_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSyncServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gosync.GoSync/PublishEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSyncServer).PublishEvent(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gosync.GoSync",
	HandlerType: (*GoSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinSession",
			Handler:    _GoSync_JoinSession_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _GoSync_PublishEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _GoSync_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("gosync.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0x51, 0xab, 0xd3, 0x30,
	0x18, 0x5d, 0xae, 0xdb, 0x6a, 0xbf, 0x55, 0xaf, 0x37, 0xa2, 0xc4, 0x81, 0xd0, 0x05, 0x1f, 0x26,
	0xc2, 0x90, 0xf9, 0x20, 0x82, 0x20, 0x0c, 0x64, 0x4e, 0x50, 0x66, 0xe7, 0xfb, 0xe8, 0xba, 0xd8,
	0x55, 0xda, 0xa4, 0x2e, 0x5f, 0x85, 0xfa, 0xeb, 0xfc, 0x69, 0xd2, 0x34, 0xe9, 0x9c, 0x7b, 0x93,
	0xfb, 0x96, 0x9c, 0x73, 0x92, 0x73, 0xbe, 0xd3, 0x14, 0x82, 0x54, 0xe9, 0x5a, 0x26, 0xb3, 0xf2,
	0xa8, 0x50, 0xd1, 0x61, 0xbb, 0xe3, 0xbf, 0xe0, 0xc1, 0x52, 0xe0, 0xfb, 0x9f, 0x42, 0xa2, 0x8e,
	0xc4, 0x8f, 0x4a, 0x68, 0xa4, 0xcf, 0xc1, 0xd3, 0x42, 0xeb, 0x4c, 0x49, 0x46, 0x42, 0x32, 0x1d,
	0xcd, 0xaf, 0x67, 0xf6, 0xec, 0xa6, 0x85, 0x23, 0xc7, 0xd3, 0x27, 0x70, 0x37, 0x6d, 0xce, 0x6c,
	0xb3, 0x3d, 0xbb, 0x0a, 0xc9, 0x74, 0x10, 0x79, 0x66, 0xbf, 0xda, 0xd3, 0x10, 0x02, 0x89, 0xe5,
	0x16, 0xb3, 0x42, 0x6c, 0x8f, 0x88, 0x6c, 0x60, 0x68, 0x90, 0x58, 0x7e, 0xcd, 0x0a, 0x11, 0x21,
	0xf2, 0x37, 0xe0, 0x2f, 0x37, 0x9f, 0x84, 0xd6, 0x71, 0x2a, 0x28, 0x85, 0x7e, 0x23, 0x35, 0x8e,
	0x83, 0xc8, 0xac, 0x29, 0x03, 0xaf, 0x68, 0x69, 0xd6, 0x0f, 0xc9, 0xd4, 0x8f, 0xdc, 0x96, 0x7f,
	0x03, 0xcf, 0x66, 0xa1, 0x4f, 0x01, 0x6c, 0x9a, 0x26, 0x04, 0x31, 0x3a, 0xdf, 0x22, 0xab, 0x3d,
	0x9d, 0x40, 0xe0, 0x68, 0x19, 0x17, 0xc2, 0xa4, 0xf4, 0xa3, 0x91, 0xc5, 0x3e, 0xc7, 0x85, 0x68,
	0x86, 0x68, 0x92, 0x1e, 0x94, 0x46, 0x76, 0xa7, 0xf5, 0x91, 0x58, 0x7e, 0x50, 0x1a, 0xf9, 0x04,
	0x46, 0x1f, 0x55, 0x26, 0x5d, 0x33, 0x14, 0xfa, 0xe6, 0x92, 0xd6, 0xc5, 0xac, 0xf9, 0x17, 0xf0,
	0x5b, 0x49, 0x99, 0xd7, 0xb7, 0x53, 0x1d, 0x3f, 0xc0, 0xfd, 0x75, 0xb5, 0xcb, 0x33, 0x7d, 0xf8,
	0x8f, 0x4f, 0xf2, 0xe2, 0x54, 0xda, 0x95, 0x91, 0xde, 0x38, 0x69, 0x57, 0xf6, 0xa9, 0xc7, 0x6b,
	0xb8, 0xd7, 0x39, 0xe9, 0x2a, 0xc7, 0xf9, 0x6f, 0x02, 0xc3, 0xa5, 0xda, 0xd4, 0x32, 0xa1, 0xaf,
	0xdb, 0xd9, 0x5d, 0xcf, 0x0f, 0xdd, 0x35, 0x7f, 0x15, 0x32, 0xbe, 0x39, 0x07, 0xcb, 0xbc, 0xe6,
	0x3d, 0xfa, 0x16, 0xfc, 0xee, 0x4d, 0x51, 0xd6, 0xb9, 0xff, 0xf3, 0xcc, 0xc6, 0x97, 0xb9, 0x78,
	0xef, 0x25, 0xa1, 0xef, 0x20, 0xb0, 0x91, 0x8c, 0x9c, 0x3e, 0x76, 0xb2, 0xf3, 0x4a, 0xc6, 0x8f,
	0x2e, 0xf0, 0x66, 0x00, 0xde, 0x5b, 0x3c, 0x03, 0x66, 0x99, 0xef, 0x71, 0xad, 0x13, 0x55, 0x94,
	0x15, 0x66, 0x32, 0x9d, 0x25, 0xaa, 0x58, 0xd8, 0xd9, 0xd6, 0x64, 0x37, 0x34, 0xff, 0xc1, 0xab,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0x36, 0x61, 0x5f, 0x17, 0x03, 0x00, 0x00,
}
